CREATE or REPLACE PROCEDURE DCUA166.DQP_STATUS_LOG_UPDATE 
    ( 
    V_RUN_NUMBER INTEGER, 
    V_RUN_DATE DATE,
    V_CDE_NAME VARCHAR2, 
    V_TOTAL_RECS_INSERTED INTEGER,
    V_STATUS_DESC VARCHAR2, 
    V_STATUS_FLAG  VARCHAR2
    )
IS
    PROC_NAME VARCHAR2(40):= 'DQ_STATUS_LOG_UPDATE ';
------------ LOCAL VARIABLES

BEGIN
    INSERT INTO DQ_STATUS_LOG 
        (RUN_NUMBER, RUN_DATE, CDE_NAME, TOTAL_RECS_INSERTED, STATUS_DESC,STATUS_FLAG)
    VALUES (V_RUN_NUMBER, V_RUN_DATE, V_CDE_NAME, V_TOTAL_RECS_INSERTED, V_STATUS_DESC, V_STATUS_FLAG );
    
    commit;

	EXCEPTION
		WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE ('An error was encountered in procedure ' || PROC_NAME || ' - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
		raise_application_error(-20001,'An error was encountered in procedure '|| PROC_NAME || ' - '||SQLCODE||' -ERROR- '||SQLERRM);
END;