-- Get CDE Reference Values for Given CDE_RULEID
CREATE OR REPLACE TYPE DCUA166.CDE_REF_REC_TYPE AS OBJECT--Type to hold CDE Attributes
(
	CDE_NAME VARCHAR2(40),
	CDE_ID INTEGER,
	RULE_NAME VARCHAR2(40),
	RULE_ID INTEGER,
	DOMAIN_NAME VARCHAR2(40),
	DOMAIN_ID INTEGER
)
/
CREATE OR REPLACE FUNCTION DCUA166.fGET_CDE_REFERENCE_DATA (CDE_RULEID IN INTEGER)
return CDE_REF_REC_TYPE
AS 
   CDE_REF_RECORD CDE_REF_REC_TYPE;
BEGIN
    CDE_REF_RECORD:=new CDE_REF_REC_TYPE (null, null, null, null, null,null); -- init the record to nulls
    SELECT b.CDE_NAME, b.CDE_ID, c.RULE_NAME, c.RULE_ID, d.DOMAIN_NAME, d.DOMAIN_ID
    INTO CDE_REF_RECORD.CDE_NAME, CDE_REF_RECORD.CDE_ID, CDE_REF_RECORD.RULE_NAME,
		 CDE_REF_RECORD.RULE_ID,CDE_REF_RECORD.DOMAIN_NAME, CDE_REF_RECORD.DOMAIN_ID
   FROM CDE_RULE a
   INNER JOIN CDE b ON (a.CDE_ID = b.CDE_ID)
   INNER JOIN RULE c ON (a.RULE_ID = c.RULE_ID)
   INNER JOIN DOMAIN d ON (b.DOMAIN_ID = d.DOMAIN_ID)
	
   WHERE a.CDE_RULE_ID = CDE_RULEID;

   RETURN (CDE_REF_RECORD);  
   
END;